
package com.tsg.netsuite.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-18T14:58:00.473-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "exceededRequestSizeFault", targetNamespace = "urn:faults_2022_1.platform.webservices.netsuite.com")
public class ExceededRequestSizeFault_Exception extends Exception {
    
    private com.tsg.netsuite.client.ExceededRequestSizeFault exceededRequestSizeFault;

    public ExceededRequestSizeFault_Exception() {
        super();
    }
    
    public ExceededRequestSizeFault_Exception(String message) {
        super(message);
    }
    
    public ExceededRequestSizeFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededRequestSizeFault_Exception(String message, com.tsg.netsuite.client.ExceededRequestSizeFault exceededRequestSizeFault) {
        super(message);
        this.exceededRequestSizeFault = exceededRequestSizeFault;
    }

    public ExceededRequestSizeFault_Exception(String message, com.tsg.netsuite.client.ExceededRequestSizeFault exceededRequestSizeFault, Throwable cause) {
        super(message, cause);
        this.exceededRequestSizeFault = exceededRequestSizeFault;
    }

    public com.tsg.netsuite.client.ExceededRequestSizeFault getFaultInfo() {
        return this.exceededRequestSizeFault;
    }
}
