
package com.tsg.netsuite.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-18T14:58:00.438-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "exceededRecordCountFault", targetNamespace = "urn:faults_2022_1.platform.webservices.netsuite.com")
public class ExceededRecordCountFault_Exception extends Exception {
    
    private com.tsg.netsuite.client.ExceededRecordCountFault exceededRecordCountFault;

    public ExceededRecordCountFault_Exception() {
        super();
    }
    
    public ExceededRecordCountFault_Exception(String message) {
        super(message);
    }
    
    public ExceededRecordCountFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public ExceededRecordCountFault_Exception(String message, com.tsg.netsuite.client.ExceededRecordCountFault exceededRecordCountFault) {
        super(message);
        this.exceededRecordCountFault = exceededRecordCountFault;
    }

    public ExceededRecordCountFault_Exception(String message, com.tsg.netsuite.client.ExceededRecordCountFault exceededRecordCountFault, Throwable cause) {
        super(message, cause);
        this.exceededRecordCountFault = exceededRecordCountFault;
    }

    public com.tsg.netsuite.client.ExceededRecordCountFault getFaultInfo() {
        return this.exceededRecordCountFault;
    }
}
