
package com.tsg.netsuite.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.1
 * 2017-12-18T14:58:00.494-07:00
 * Generated source version: 3.2.1
 */

@WebFault(name = "invalidVersionFault", targetNamespace = "urn:faults_2022_1.platform.webservices.netsuite.com")
public class InvalidVersionFault_Exception extends Exception {
    
    private com.tsg.netsuite.client.InvalidVersionFault invalidVersionFault;

    public InvalidVersionFault_Exception() {
        super();
    }
    
    public InvalidVersionFault_Exception(String message) {
        super(message);
    }
    
    public InvalidVersionFault_Exception(String message, Throwable cause) {
        super(message, cause);
    }

    public InvalidVersionFault_Exception(String message, com.tsg.netsuite.client.InvalidVersionFault invalidVersionFault) {
        super(message);
        this.invalidVersionFault = invalidVersionFault;
    }

    public InvalidVersionFault_Exception(String message, com.tsg.netsuite.client.InvalidVersionFault invalidVersionFault, Throwable cause) {
        super(message, cause);
        this.invalidVersionFault = invalidVersionFault;
    }

    public com.tsg.netsuite.client.InvalidVersionFault getFaultInfo() {
        return this.invalidVersionFault;
    }
}
